apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oidc-server-cert
  namespace: default
spec: 
  secretName: oidc-server-tls
  commonName: oidc-server.example.com
  dnsNames:
    - oidc-server.example.com
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
