apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: admin-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: oidc
  namespace: default
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io

